num: 3

spring:
  application:
    name: legion-cluster
server:
  port: 900${num}

# server
legion:
  server:
    host: 172.16.1.64
    port: 1800${num}
    detector:
      intervalInMillis: 1000
      phiConvictThreshold: 8
  cluster:
    - host: 172.16.1.64
      port: 18001

logging:
  path: logs
  file: legion-cluster
  level:
    org.springframework: warn
    org.springframework.boot.web.embedded.tomcat: info
    com.legion.net.entities.TraceLogSender: info
    org.apache.kafka: error
    io.netty: info
    com.legion: warn
    org.hibernate: warn
    reactor.netty: info
    org.synchronoss: info

# management
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: /exporter
      exposure:
        include: prometheus
    jmx:
      exposure:
        exclude: '*'
  server:
    port: 1${server.port}
